### ISSUE TITLE
gtfs2ntfs - Can not generate zipped ntfs as mentioned in doc

### ISSUE THREAD

**Issue by ArnaudOggy** [CanalTP/transit_model#186]
gtfs2ntfs - Can not generate zipped ntfs (for output) as mentioned in doc
https://github.com/CanalTP/navitia_model/blob/master/src/documentation/gtfs2ntfs.md

**Comment by datanel** [comment]
this is corrected in https://github.com/CanalTP/tartare-tools/pull/26

**Comment by woshilapin** [comment]
Meaning, the documentation has been fixed (we still cannot generate a ZIP file in output)!
