### ISSUE TITLE
more flexible GTFS stop_times reading

### ISSUE THREAD

**Issue by antoine-de** [CanalTP/transit_model#204]
Even if the `departure_time` and `arrival_time` of the `stop_times.txt` file are marked as `required` in the [gtfs specification](https://developers.google.com/transit/gtfs/reference/#stop_timestxt), the spec says:

`"If this stop is not a timepoint, use either an empty string value for the arrival_time field or provide an interpolated time. "`

The `timepoint` adds some precision:
`"For stop-time entries without specified arrival and departure times, feed consumers must interpolate arrival and departure times. Feed producers may optionally indicate that such an entry is not a timepoint (value=0) but it is an error to mark a entry as a timepoint (value=1) without specifying arrival and departure times."`

You [internal documentation](https://github.com/CanalTP/navitia_model/blob/master/src/documentation/gtfs_read.md#reading-stop_timestxt) says that some interpolation needs to be done if the arrival/departure are not provided, but I don't see where this is implemented.

For the moment the `gtfs::StopTime` object has 
```rust
struct StopTime {
    arrival_time: Time,
    departure_time: Time,
    ...
}
```
So I don't think it's possible yet to read empty departure/arrival.

Did I miss something ?

Are you ok if I implement this ?

poke @prhod

**Comment by prhod** [comment]
You're absolutely right ! It was ment to be done in the GTFS read, but no priority was given to it. If you agree on adding it, please do :pray:

**Comment by datanel** [comment]
fixed here https://github.com/CanalTP/transit_model/pull/207
