### ISSUE TITLE
Proj4 v6.1.0 breaks the build

### ISSUE THREAD

**Issue by woshilapin** [CanalTP/transit_model#252]
Between version v6.0.0 and v6.1.0 of [Proj4](https://proj4.org/), the conversion from `EPSG:28992` to `EPSG:4326` (aka `WGS84`) used for KV1 doesn't provide exactly the same results (millionth precision). We should define what version of [Proj4](https://proj4.org/) is officially supported in `transit_model`.

**Comment by woshilapin** [comment]
Note: I will provide a PR to update the tests so it supports the latest version of Proj4 6.1.0 and document what is the supported version in the `README`.

**Comment by woshilapin** [comment]
PR #253 should fix this issue.

**Comment by datanel** [comment]
I close this issue since we don't have any problem anymore
