### ISSUE TITLE
Improve error message when input file doesn't exist in 'gtfs2ntfs'

### ISSUE THREAD

**Issue by Darkham42** [CanalTP/transit_model#275]
Bonjour,

J'ai vu qu'il y avait eu un PR (PR 187) en février ajoutant ce message d'erreur mais je n'arrive pas à récupérer plus d'informations...

Du coup je lance ma commande : 
`target/release/gtfs2ntfs -i /gtfs/gtfs-test.zip -o /ntfs/ntfs-test.zip`

Et j'ai directement un retour :
`calendar_dates.txt or calendar.txt not found`

Or mon GTFS contient bien un calendar.txt (j'ai testé sur plusieurs GTFS avec tous une origine différente) et ce sont des GTFS qui s'intègrent bien dans mon navitia...

Auriez-vous une idée du soucis ? Pour information je suis sur Proj4 v6.1.0

**Comment by woshilapin** [comment]
Bonjour,

Première chose, je ne pense pas que `gtfs2ntfs` supporte l'export en ZIP. Il va te falloir un répertoire (créé à l'avance).

Deuxièmement, merci pour l'information concernant Proj4 mais Proj4 n'est pas utilisé sur le process `gtfs2ntfs` donc ça ne devrait pas influer sur ton problème.

Troisième chose, et là c'est quelque chose que tu peux tester, tu peux dézipper ton fichier `gtfs-test.zip` et donner en entrée le chemin vers le répertoire `--input gtfs-test/` (au lieu de donner un fichier ZIP).  Ça devrait te permettre de vérifier que ce n'est pas un problème avec le ZIP lui-même (il y a tellement de type de ZIP différents que nous avons constater que certains ZIP ne fonctionnent pas).

Dis-nous si ça te permet d'avancer ou pas ?

**Comment by Darkham42** [comment]
Merci @woshilapin pour ta réponse, du coup : 

- Oui j'ai vu un ticket à ce sujet donc j'ai déjà testé de créé un répertoire et d'exporter dans celui-ci en vain
- De ce que j'ai vu du code je m'en doutais mais je me suis dis que par sécurité ayant vu des issues où Proj4 était source de problème, on gagnerait du temps :)
- J'ai le même résultat en passant en input directement mon répertoire avec mes fichiers txt de mon GTFS, et même résultat.

**Comment by Darkham42** [comment]
2 erreurs du coup dans ce que j'ai essayé de faire :
gtfs2ntfs n'exporte pas de .zip du coup le output doit pointer vers un dossier
le message du calendar est un message générique, dans mon cas je n'allais pas chercher le gtfs au bon endroit :)

**Comment by woshilapin** [comment]
After discussion, the issue is more about the error message when the input file doesn't exist. Today, in `gtfs2ntfs`, when the `--input` file or folder doesn't exist, the error message is `calendar_dates.txt or calendar.txt not found` which is not really useful to understand the root of the problem.

I changed the title of this issue to reflect the problem of the error message.

**Comment by woshilapin** [comment]
I just create #320 to address this problem of error message being useless to understand the problem. I hope this will help.
