### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by datanel** [CanalTP/transit_model#329]
We could have a better Readme
- remove references to binaries once https://github.com/CanalTP/transit_model/pull/316 is merged
- complete the list of features (maybe add some examples in `./examples`)

**Comment by antoine-de** [comment]
I do agree that the documentation could be improved :stuck_out_tongue_winking_eye: 

It would for example be very nice to see the ergonomic of handling transit data. It's a killer feature, but It's impossible to know it's existence!

something like?

```rust
let transit_data = transit_model::gtfs::read_from_path("example", None, None, false).expect("impossible to read GTFS");

// get a stop by it's ID
let stop_area_idx = transit_data
    .stop_areas
    .get_idx("stoparea:1")
    .expect("impossible to find stop area");

println!("routes passing by stop stoparea:1");

// efficiently get all the routes that pass through the stop_area
for route in transit_data
    // The rust typesystem is able to guess that we are looking for the routes linked to the stop
    // because the Idx are strongly typed, thus route_idx is Idx<Route>
    .get_corresponding_from_idx(stop_area_idx)
    .into_iter()
    .map(|route_idx| &transit_data.routes[route_idx])
{
    println!(" - {}", route.name);
}
```

And maybe add a reference to the quite good [technical documentation](https://docs.rs/transit_model) ?

**Comment by datanel** [comment]
yes that's the idea

**Comment by datanel** [comment]
the readme has been updated but I think we need to provide some examples as you suggest @antoine-de
