### ISSUE TITLE
FareZone on StopPoints

### ISSUE THREAD

**Issue by prhod** [CanalTP/transit_model#35]
Actually, FareZone in navitia_models and the NTFS are available on both StopPoints and StopArea.
This issue is a reminder to remove the FareZone on the StopArea  : 
- [x] in navitia_models
- [x] in the NTFS specs

**Comment by datanel** [comment]
@prhod FareZone was removed from transit_model not NTFS specs

**Comment by woshilapin** [comment]
@datanel In NTFS specifications, the property `fare_zone_id` is specified to be exclusively used with `location_type = 0` (a stop point), so I would say the specifications are fine too. Looks like this issue could be closed?

**Comment by prhod** [comment]
As stated by @woshilapin , NTFS explaines it so the issue is no more relevant. I'm closing it.
