### ISSUE TITLE
Missing documentation about some APIs

### ISSUE THREAD

**Issue by woshilapin** [CanalTP/transit_model#444]
Some APIs of the `transit_model` are not documented (at least, not in `src/documentation`, the code itself might be partially documented). Here a (possibly non-exhaustive) list:
- `transit_model_collections::Collections::try_merge()`
- `transit_model_collections::Collections::restrict_period()`
- `transit_model::apply_rules::apply_rules()`
- `transit_model::hellogo_fares::enrich_with_hellogo_fares()`
- `transit_model::ntfs::filter::filter()`
- `transit_model::merge_stop_areas::merge_stop_areas()`
- `transit_model::transfers::generates_transfers()`

All of the above APIs have been implemented with a lot of business rules that are not documented. It would be nice to know and explain why and how they are implemented and what decisions have been made.

**Comment by datanel** [comment]
I think this issue can be closed @woshilapin

**Comment by woshilapin** [comment]
I believe you're right. I'm closing the issue.
