### ISSUE TITLE
gtfs2netexfr installation issue

### ISSUE THREAD

**Issue by jvanoost** [CanalTP/transit_model#646]
Hi,

I'm a great newb with rust and cargo
I followed the install procedure by install PROJ and then clang and libssl-dev => that's OK

I tried to install gtfs2netexfr and get this when I lauched the command
```
~/home/gtfs2netexfr$ cargo install gtfs2netexfr
    Updating crates.io index
error: could not find `gtfs2netexfr` in registry `https://github.com/rust-lang/crates.io-index`

```

how can I solve this ?
Thanks

**Comment by datanel** [comment]
@jvanoost is it good for you now?

**Comment by jvanoost** [comment]
not yet, but my fault

I made a mistake while wanted to add proj to the path.
I'm on it to correct
But all you give me is ok, so I'm pretty sure it will be ok ;)

**Comment by datanel** [comment]
sorry I'm not sure to understand well.

Your question is how to test the command with your GTFS Lille or how to test the netex produced ?

**Comment by jvanoost** [comment]
Sorry it wasn't clear
the question was about testing the netex produced.
I tried to zip and upload it on : http://appli.chouette.mobi/ but it got an error

**Comment by datanel** [comment]
I don't know what tool you can test with but you can test that the XML produced has a valid schema.
see https://github.com/CanalTP/transit_model/blob/master/tests/write_netex_france.rs#L79

with xmllint
`xmllint --noout --nonet --huge --schema NeTEx_publication.xsd your_produced_netex`

NetEx_publication.xsd coming from https://github.com/NeTEx-CEN/NeTEx/blob/348033a470ae7cfc50c57c911b0e786b52dd85bc/xsd/NeTEx_publication.xsd

**Comment by jvanoost** [comment]
Ok thanks a lot ! I close the issue !
