### ISSUE TITLE
merge-ntfs 

### ISSUE THREAD

**Issue by alibouaziz** [CanalTP/transit_model#651]
if i have multiple NTFS/coverage, what should i do ?
i can't send multiple NTFS to tyr-api, because it [clean](https://github.com/CanalTP/navitia/blob/dev/source/ed/ed_persistor.cpp#L303) database, and then insert.
thanks

**Comment by prhod** [comment]
Hello @alibouaziz 
You are right, you need to merge NTFS prior to sending them to Tyr. Merging several NTFS together can be tricky depending on how you want to deal with conflicting object ids, and the liking with other data sources you may want to apply (like real time or disruptions).
This kind of operations is available as a part of our paid services, and not available as OpenSource components. Feel free to contact sales@kisio.com about this!

**Comment by woshilapin** [comment]
@alibouaziz Does it answer your question? If not, don't hesitate to reopen the issue and give us some more context and information.
