### ISSUE TITLE
Error reading "./ntfs/feed_infos.txt"

### ISSUE THREAD

**Issue by sign0** [CanalTP/transit_model#712]
Hello,

I am using the gtfs2ntfs tool for the first time with the [latest GTFS 'fr-nw'](https://navitia.opendatasoft.com/explore/dataset/fr-nw/files/e5b3dddb45bb3f8dbeb4c8dcbf7624ee/download/), but unfortunately I get this error message :

```
Oct 26 08:25:34.264 INFO Writing feed_infos.txt
Error reading "./ntfs/feed_infos.txt"
No such file or directory (os error 2)
```

My command line is :
```
gtfs2ntfs --input ./gtfs/ --output ./ntfs
```

Do you know how I can resolve this problem ?

**Comment by ArnaudOggy** [comment]
Have you created your output folder (./ntfs) with a `mkir` before?

**Comment by sign0** [comment]
Indeed I had not created the output folder,
I thought the tool did it automatically ...

Thanks for the very quick response! :)

**Comment by ArnaudOggy** [comment]
it's true that the tool should create it itself :wink: 
Have fun !
