### ISSUE TITLE
Allow reading GTFS csv files with a flexible option for columns number

### ISSUE THREAD

**Issue by fchabouis** [CanalTP/transit_model#748]
Hi,

I am Francis Chabouis, working as a developper for transport.data.gouv.fr.
We are using gtfs2netexfr to generate NeTEx files from the GTFS available on our plateform.

For the moment I didn't see an option to read GTFS files with a flexible option, meaning a way to convert GTFS files containing CSV with a non-constant number of columns.

It is unfortunately possible that provided CSV files have missing columns on some rows, and we would like gtfs2netexfr to be able to handle such cases.

We have an [issue](https://github.com/etalab/transport-site/issues/1527) on our project, with a an example of such a GTFS.

Thank you and let me know if you need further explanations on this request.

**Comment by woshilapin** [comment]
We'll take a look. Seems like an easy fix. Let us come back to you.

**Comment by woshilapin** [comment]
Fixed by #770.
