### ISSUE TITLE
Coordonnées WGS

### ISSUE THREAD

**Issue by ue71603** [CanalTP/transit_model#765]
La solution exporte tous les coordonnées dans un projection Lambert https://epsg.io/2154
Ca ne fonctionne pas au dehors de la France.
Il serait mieux d'utiliser les coordonnées WGS (au moins en addition)
 

Maintenant:
					<Centroid>
						<Location>
							<gml:pos srsName="EPSG:2154">0.00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003026405013 0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000007725596546446257</gml:pos>
						</Location>
					</Centroid>

Exigé:

					<Centroid>
						<Location>
						<Longitude>3.026405013</Longitude>
						<Latitude>77.25596546446257</Latitude>
						</Location>
					</Centroid>

Ou:
					<Centroid>
						<Location>
						<Longitude>3.026405013</Longitude>
						<Latitude>77.25596546446257</Latitude>
							<gml:pos srsName="EPSG:2154">0.00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003026405013 0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000007725596546446257</gml:pos>
						</Location>
					</Centroid>

**Comment by pbougue** [comment]
Hello,

We can do this in English (this repo is full :gb: currently to offer a larger access).
Nous pouvons discuter en Anglais si besoin (ce dépôt est entièrement en :gb: pour faciliter l'accès au plus grand nombre).

Pouvez-vous préciser ce que vous faites comme usage, quel est votre but (global, et également une fonctionnalité précise si besoin) ?

**Comment by ue71603** [comment]
Hi
your coordinates assume that it is always about French data.  EPSG:2154 can only be used for France (bounding box). If we want to do e.g. a part of Austria EPSG:2154 is not really useful. To have the WGS84 coordinates in Latitude and Longitude would be a lot better. If you want, you can do both.

We are currently trying to transform a GTFS file from Austria into a NeTEx file that is consuable by our importer.

The data we want to transform are: https://data.oebb.at/oebb?dataset=uddi:cd36722f-1b9a-11e8-8087-b71b4f81793a
Kind regards
Matthias

**Comment by woshilapin** [comment]
Hi,

So you're trying to produce Austrian NeTEx, but our binary is producing French NeTEx, hence the name of the binary `gtfs2netexfr`. From what we understood, NeTEx is a framework and there has been specificities for each implementation (called profiles I think), sometimes driven by countries, sometimes driven by companies. `gtfs2netexfr` is capable of producing French profile of NeTEx.

Producing a different profile might require significant work. We do not have the resources neither the goal to do this kind of improvement at the moment. However, we'd be willing to provide guidance and review if you do have the time to invest and implement this functionality (it is an open-source project, so you're welcome to contribute and improve the code). Some important parts of the code could be reused to do that.

Does it answer your question?

**Comment by ue71603** [comment]
Thanks for the offer, but we will use a different more general converter then. And also with the code we would be able to change it ourselves. This issue was mostly to provide you feedback, if you wanted to become amore general converter.

**Comment by prhod** [comment]
Thanks for your feedback @ue71603 ! For the time being we won't make a generalization of the Netex conversion, but it will be probably done when the needs arise. We are open for contributions in the mean time of course! :wink: 
I wish you find the right converter for your use case.
Best regards
